FROM python:3.13-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/src /app/src

CMD ["celery", "-A", "src.workers.celery_app:celery", "worker", "--loglevel=info"]